
import mongoose from 'mongoose';

let SinisterSchema = new mongoose.Schema({
	idPolicy: {type: String},
	policy: { type: mongoose.Schema.ObjectId, ref: "Policy"},
	policyData: {type: Object},
	idPolicyAnnex: {type: String},
	annexData: {type: Object},
	idClient: {type: String},
	clientData: {type: Object},
	idRecipient: {type: String}, //CLIENT, BUSINESS, INSURANCE, USER
	recipient: {type: Object},
	typeRecipient: {type: String},
	compName: {type: String},
	clientInsured: {type: String},
	beneficiary: {type: String},
	dateSinister: {type: String},
	dateNotification: {type: String},
	trackingDate: {type: Date},
	beneficiary: {type: String},
	idRamo: {type: String},
	ramo: { type: mongoose.Schema.ObjectId, ref: "Ramo"},
	sinisterState: {type: String},
	settlementDate: {type: Date},
	approvalDate: {type: Date},
	checkApproved: {type: Boolean},
	item: {
		idSinister: {type: String},
		sinister: { type: mongoose.Schema.ObjectId, ref: "Sinister"},
		workshop: {type: String},
		arrangement: { type: String},
		rasa: {type: String},
		sinisterValue: {type: Number},
		rc: {type: String},
		deductibleValue: {type: Number},
		depreciation: {type: String},
		others1: {type: String},
		others2: {type: String},
		others3: {type: String},
		notCovered: {type: String},
		observationNotCovered: {type: String},
		liquidation: {type: Number},
		liquidationDate: {type: Date},
		deliverDate: {type: Date},
		idCar: {type: String},
		carDetails: { type: Object},
		sinisterDiagnosis: {type: String},
		sinisterMap: {
			longitude: {type: String},
			latitude: {type: String}
		},
		idClient: {type: Object},
		client: { type: mongoose.Schema.ObjectId, ref: "Client"},
		dataPatient: {type: Object},
		sinisterDiagnosis: {type: String},
		observationNotCovered: {type: String},
		observationLiquidation: {type: String},
		liquidationValue: {type: Number},
		liquidationDate: {type: Date},
		deliverDate: {type: Date},
		lastDocumentSent: {type: String},
		items: [{
			idSinisterGeneral: {type: String},
			sinisterGeneral: { type: mongoose.Schema.ObjectId, ref: "SinisterGeneral"},
			idSinisterDocumentationRamo: {type: String},
			sinisterDocumentationRamo: { type: mongoose.Schema.ObjectId, ref: "sinisterDocumentationRamo"},
			quantity: {type: Number},
			description: { type: String},
			sendDate: {type: Date},
			responsibleReception: {type: String},
			receptionDate: {type: Date},
			numberAllBilling: {type: Number},
			totalBillingValue: {type: Number}
		}]
	},
	dateCreate: {type: Date, require: true},
	userCreate: {type: String, require: true},
	branchCreate: {type: String, require: true},
	dateUpdate: {type: Date, require: true},
	userUpdate: {type: String, require: true}
});


export default mongoose.model('Sinister', SinisterSchema)
